name: CI
on:
  push:
    branches: [ "bungeecord" ]
  pull_request:
    branches: [ "bungeecord" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Run every 5 hours
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ secrets.FINE_GRAINED_PAT }}  # Use fine-grained PAT for checkout
      - name: Set up OpenJDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Debug - List directory contents
        run: ls -la
      - name: Run BungeeCord and playit with 30-second commits and workflow deletion
        if: "!contains(github.event.head_commit.message, 'Auto commit every 30 seconds')"
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
          PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET_3 }}
          HOSTNAME: ${{secrets.CF_TUNNEL_HOSTNAME}}
          HOSTNAME_2: ${{secrets.CF_TUNNEL_HOSTNAME_2}}
          HOSTNAME_3: ${{secrets.CF_TUNNEL_HOSTNAME_3}}
          HOSTNAME_4: ${{secrets.CF_TUNNEL_HOSTNAME_4}}

        run: |
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update && sudo apt-get install cloudflared
          cloudflared access tcp --hostname ${HOSTNAME} --url localhost:25566 > /dev/null &
          cloudflared access tcp --hostname ${HOSTNAME_2} --url localhost:25569 > /dev/null &
          cloudflared access tcp --hostname ${HOSTNAME_3} --url localhost:25570 > /dev/null &
          cloudflared access tcp --hostname ${HOSTNAME_4} --url localhost:25571 > /dev/null &

          cd $GITHUB_WORKSPACE
          chmod +x playit-linux-amd64
          echo "$PLAYIT_SECRET" > playit.toml
          echo "Starting BungeeCord..."
          java -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Xms16G -Xmx16G -jar FlameCord-JDK8.jar nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
          SPIGOT_PID=$!
          echo "BungeeCord started with PID $SPIGOT_PID"
          echo "Starting playit..."
          ./playit-linux-amd64 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
          PLAYIT_PID=$!
          echo "playit started with PID $PLAYIT_PID"
          
          # Function to commit and push changes
          commit_and_push() {
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A  # Stage all changes
            git reset -- playit.toml  # Unstage playit.toml
            git reset -- playit.log
            git reset -- logs/
            git commit -m "Auto commit every 30 seconds" || echo "No changes to commit"
            git push https://x-access-token:${FINE_GRAINED_PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:bungeecord
          }
          
          # Function to delete auto-commit workflow runs
          delete_auto_commit_workflows() {
            workflow_ids=$(curl -s -H "Authorization: token $FINE_GRAINED_PAT" \
              "https://api.github.com/repos/${REPO}/actions/runs" | \
              jq '.workflow_runs[] | select(.head_commit.message | contains("Auto commit every 30 seconds")) | .id')
            for id in $workflow_ids; do
              echo "Deleting workflow run $id"
              curl -s -X DELETE -H "Authorization: token $FINE_GRAINED_PAT" \
                "https://api.github.com/repos/${REPO}/actions/runs/$id"
            done
          }
          
          # Loop to commit and delete workflows every 30 seconds
          while true; do
            sleep 30
            commit_and_push
            delete_auto_commit_workflows
            
            # Check if processes are still running
            if ! kill -0 $SPIGOT_PID 2>/dev/null || ! kill -0 $PLAYIT_PID 2>/dev/null; then
              echo "One of the processes has finished. Restarting the workflow."
              exit 0  # Exit with error code to trigger a workflow restart
            fi
          done
      - name: Trigger new workflow
        if: always()
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${REPO}/dispatches \
            -d '{"event_type": "restart_workflow"}'

